version: "3.3"
services:
    #PHP Service
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        image: crud/php
        container_name: backend
        depends_on:
            - crud_db
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: backend
            SERVICE_TAGS: dev
        working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html/
            - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
        networks:
            - app-network

    frontend:
        image: node:current-alpine
        container_name: frontend
        working_dir: /home/node/app
        ports:
            - "8080"
        volumes:
            - ../frontend:/home/node/app
        environment:
            NODE_ENV: development
        command: "npm run serve"
        networks:
            - app-network

    #Nginx Service
    webserver:
        depends_on:
            - backend
            - frontend
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        networks:
            - app-network

    # The Database
    crud_db:
        image: postgres:10.1
        container_name: "crud_db"
        hostname: "crud_db"
        extra_hosts:
            - "dockerhost:127.0.0.1"
        environment:
            - 'DB_USER=postgres'
            - 'DB_PASS=postgres'
            - 'DB_NAME=postgres'
        ports:
            - "5432:5432"
        restart: 'always'

#Docker Networks
networks:
    app-network:
        driver: bridge
